### ISSUE TITLE
error: cannot run atom: No such file or directory

### ISSUE THREAD

**Issue by antoniomedrano** [githubteacher/git-essentials-may-2016#12]
I have atom installed, yet when I run `git commit` I get:
error: cannot run atom: No such file or directory
error: unable to start editor 'atom'

**Comment by antoniomedrano** [comment]
this is after having run the following command:
`git config --global core.editor "atom --wait"`

**Comment by marti1125** [comment]
try to verify path or run in the terminal $ atom and them atom should be open
![atomr](https://cloud.githubusercontent.com/assets/223240/15051218/187960c4-12bd-11e6-8bfb-db7c136d521a.png)

**Comment by antoniomedrano** [comment]
Actually, resolved it by doing this:
http://stackoverflow.com/a/23666354/1487188

**Comment by jessenovotny** [comment]
I don't have Atom installed and never have. Not sure why git is trying to open Atom. How do I change this to Sublime Text?
